session:
  host: http://localhost:9892
  account: 2928097582
  authKey: paimon-bot-auth-key
  websocket: True

name: Paimon
debug: False
banner: True
master: 1490457324

log:
  sink: ./log
  level: 10
  enqueue: True
  format: "|{time:HH:mm:ss}|{level.icon}|{message}"
  rotation: "5 MB"
  retention: "1 days"
  encoding: "utf8"